# =============================================================================
# {{PROJECT_NAME}} Service Configuration
# Read by install.sh — re-run install.sh after modifying this file.
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# =============================================================================

# ---------------------------------------------------------------------------
# Project identity
# ---------------------------------------------------------------------------
PROJECT_NAME="{{PROJECT_NAME}}"
PROJECT_DIR="{{PROJECT_DIR}}"

# ---------------------------------------------------------------------------
# Runtime users
# ---------------------------------------------------------------------------
RUN_USER="{{RUN_USER}}"
RUN_GROUP="{{RUN_GROUP}}"

# ---------------------------------------------------------------------------
# Runtime binaries (auto-detected if empty; set these if auto-detection fails)
# ---------------------------------------------------------------------------
# {{IF HAS_NODE}}
# NODE_BIN={{NODE_BIN}}
# {{ENDIF HAS_NODE}}
# {{IF HAS_PYTHON}}
# VENV_PYTHON={{VENV_PYTHON}}
# {{ENDIF HAS_PYTHON}}

# ---------------------------------------------------------------------------
# Ports
# ---------------------------------------------------------------------------
# {{IF HAS_BACKEND}}
BACKEND_PORT={{BACKEND_PORT}}
# {{ENDIF HAS_BACKEND}}
# {{IF HAS_FRONTEND}}
FRONTEND_PORT={{FRONTEND_PORT}}
# {{ENDIF HAS_FRONTEND}}

# ---------------------------------------------------------------------------
# Health check URLs (used by healthcheck.sh and install.sh readiness probes)
# ---------------------------------------------------------------------------
# {{IF HAS_BACKEND}}
BACKEND_HEALTH_URL="http://localhost:${BACKEND_PORT:-{{BACKEND_PORT}}}/health"
BACKEND_HEALTH_FALLBACK_URL="http://localhost:${BACKEND_PORT:-{{BACKEND_PORT}}}/"
# {{ENDIF HAS_BACKEND}}
# {{IF HAS_FRONTEND}}
FRONTEND_HEALTH_URL="http://localhost:${FRONTEND_PORT:-{{FRONTEND_PORT}}}/"
# {{ENDIF HAS_FRONTEND}}

# ---------------------------------------------------------------------------
# Watchdog
# ---------------------------------------------------------------------------
WATCHDOG_INTERVAL={{WATCHDOG_INTERVAL}}        # Health check interval (seconds)
WATCHDOG_FAIL_THRESHOLD={{WATCHDOG_FAIL_THRESHOLD}}   # Consecutive failures before restart
WATCHDOG_STATE_DIR=/tmp     # Directory for failure counter files

# ---------------------------------------------------------------------------
# Nginx reverse proxy (leave NGINX_DOMAIN empty to skip auto-configuration)
# ---------------------------------------------------------------------------
NGINX_DOMAIN="{{NGINX_DOMAIN}}"
NGINX_SITE_NAME="{{NGINX_SITE_NAME}}"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_DIR={{LOG_DIR}}                # Relative to project root
LOG_MAX_SIZE={{LOG_MAX_SIZE}}            # Max size per log file before rotation
LOG_ROTATE_COUNT={{LOG_ROTATE_COUNT}}          # Number of rotated files to keep

# ---------------------------------------------------------------------------
# Deployment mode: "systemd" or "docker"
# ---------------------------------------------------------------------------
DEPLOY_MODE="{{DEPLOY_MODE}}"

# ---------------------------------------------------------------------------
# Project structure: "separated" (backend/ + frontend/) or "monolith"
# ---------------------------------------------------------------------------
PROJECT_STRUCTURE="{{PROJECT_STRUCTURE}}"

# ---------------------------------------------------------------------------
# Framework identifiers (used by deploy.sh for build/start commands)
# ---------------------------------------------------------------------------
# {{IF HAS_BACKEND}}
BACKEND_FRAMEWORK="{{BACKEND_FRAMEWORK}}"
BACKEND_SUBDIRECTORY="{{BACKEND_SUBDIRECTORY}}"
BACKEND_START_COMMAND="{{BACKEND_START}}"
# {{ENDIF HAS_BACKEND}}
# {{IF HAS_FRONTEND}}
FRONTEND_FRAMEWORK="{{FRONTEND_FRAMEWORK}}"
FRONTEND_SUBDIRECTORY="{{FRONTEND_SUBDIRECTORY}}"
FRONTEND_START_COMMAND="{{FRONTEND_START}}"
FRONTEND_BUILD_COMMAND="{{BUILD_COMMAND}}"
# {{ENDIF HAS_FRONTEND}}

# ---------------------------------------------------------------------------
# Package manager: "npm", "yarn", "pnpm", "pip", "pipenv", "poetry", "conda"
# ---------------------------------------------------------------------------
# {{IF HAS_NODE}}
NODE_PACKAGE_MANAGER="{{NODE_PACKAGE_MANAGER}}"
# {{ENDIF HAS_NODE}}
# {{IF HAS_PYTHON}}
PYTHON_PACKAGE_MANAGER="{{PYTHON_PACKAGE_MANAGER}}"
# {{ENDIF HAS_PYTHON}}
