# {{PROJECT_NAME}} nginx config v1
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# HTTP-only configuration (no SSL)

# {{IF HAS_BACKEND}}
upstream {{PROJECT_NAME}}_backend {
    server 127.0.0.1:{{BACKEND_PORT}};
    keepalive 32;
}
# {{ENDIF HAS_BACKEND}}

# {{IF HAS_FRONTEND}}
upstream {{PROJECT_NAME}}_frontend {
    server 127.0.0.1:{{FRONTEND_PORT}};
    keepalive 32;
}
# {{ENDIF HAS_FRONTEND}}

server {
    listen 80;
    server_name {{NGINX_DOMAIN}};

    client_max_body_size 50m;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # {{IF HAS_BACKEND}}
    # Backend API proxy
    location /api/ {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        # SSE/streaming support
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }

    location /health {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
    # {{ENDIF HAS_BACKEND}}

    # {{IF HAS_FRONTEND}}
    location / {
        proxy_pass http://{{PROJECT_NAME}}_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # SSE/streaming: long-running connections
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }
    # {{ENDIF HAS_FRONTEND}}

    # {{IF_NOT HAS_FRONTEND}}
    location / {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }
    # {{ENDIF_NOT HAS_FRONTEND}}
}
