# {{PROJECT_NAME}} nginx config v1
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}

# {{IF HAS_BACKEND}}
# Backend API upstream
upstream {{PROJECT_NAME}}_backend {
    server 127.0.0.1:{{BACKEND_PORT}};
    keepalive 32;
}
# {{ENDIF HAS_BACKEND}}

# {{IF HAS_FRONTEND}}
# Frontend upstream
upstream {{PROJECT_NAME}}_frontend {
    server 127.0.0.1:{{FRONTEND_PORT}};
    keepalive 32;
}
# {{ENDIF HAS_FRONTEND}}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name {{NGINX_DOMAIN}};

    ssl_certificate     {{NGINX_SSL_CERT}};
    ssl_certificate_key {{NGINX_SSL_KEY}};
{{NGINX_SSL_EXTRA}}

    # Allow large request bodies (file uploads, base64 payloads)
    client_max_body_size 50m;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # {{IF HAS_BACKEND}}
    # Backend API proxy — route /api/ requests to backend
    location /api/ {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        # SSE/streaming support for API endpoints
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }

    # Backend health endpoint
    location /health {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
    # {{ENDIF HAS_BACKEND}}

    # {{IF HAS_FRONTEND}}
    # Frontend proxy — all other requests
    location / {
        proxy_pass http://{{PROJECT_NAME}}_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # SSE/streaming: long-running connections
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }
    # {{ENDIF HAS_FRONTEND}}

    # {{IF_NOT HAS_FRONTEND}}
    # Monolith proxy — all requests to backend
    location / {
        proxy_pass http://{{PROJECT_NAME}}_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
        chunked_transfer_encoding on;
    }
    # {{ENDIF_NOT HAS_FRONTEND}}
}

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name {{NGINX_DOMAIN}};

    # Allow ACME challenges for cert renewal
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
