# =============================================================================
# {{PROJECT_NAME}} — Node.js Application Dockerfile
# Framework: {{FRONTEND_FRAMEWORK}}
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# =============================================================================

# ---------------------------------------------------------------------------
# Stage 1: Dependencies
# ---------------------------------------------------------------------------
FROM node:{{NODE_VERSION}}-alpine AS deps

WORKDIR /app

# Copy package files for dependency caching
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./

# Install dependencies based on detected package manager
# {{IF PM_NPM}}
RUN npm ci --production=false
# {{ENDIF PM_NPM}}
# {{IF PM_YARN}}
RUN yarn install --frozen-lockfile
# {{ENDIF PM_YARN}}
# {{IF PM_PNPM}}
RUN corepack enable && pnpm install --frozen-lockfile
# {{ENDIF PM_PNPM}}

# ---------------------------------------------------------------------------
# Stage 2: Build
# ---------------------------------------------------------------------------
FROM node:{{NODE_VERSION}}-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set build-time environment variables
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Run build command
RUN {{BUILD_COMMAND}}

# ---------------------------------------------------------------------------
# Stage 3: Production runtime
# ---------------------------------------------------------------------------
FROM node:{{NODE_VERSION}}-alpine AS runner

WORKDIR /app

# Create non-root user for security
RUN addgroup --system --gid 1001 appgroup && \
    adduser --system --uid 1001 appuser

# Set production environment
ENV NODE_ENV=production
ENV PORT={{FRONTEND_PORT}}

# Copy built artifacts and production dependencies
# {{IF FRAMEWORK_NEXTJS}}
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
# {{ENDIF FRAMEWORK_NEXTJS}}
# {{IF FRAMEWORK_NUXTJS}}
COPY --from=builder /app/.output ./.output
# {{ENDIF FRAMEWORK_NUXTJS}}
# {{IF FRAMEWORK_REACT}}
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
# {{ENDIF FRAMEWORK_REACT}}
# {{IF FRAMEWORK_VUE}}
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
# {{ENDIF FRAMEWORK_VUE}}
# {{IF FRAMEWORK_EXPRESS}}
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# {{ENDIF FRAMEWORK_EXPRESS}}

# Set ownership
RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE {{FRONTEND_PORT}}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:{{FRONTEND_PORT}}/ || exit 1

# {{IF FRAMEWORK_NEXTJS}}
CMD ["node", "server.js"]
# {{ENDIF FRAMEWORK_NEXTJS}}
# {{IF FRAMEWORK_NUXTJS}}
CMD ["node", ".output/server/index.mjs"]
# {{ENDIF FRAMEWORK_NUXTJS}}
# {{IF FRAMEWORK_REACT}}
CMD ["npx", "serve", "-s", "build", "-l", "{{FRONTEND_PORT}}"]
# {{ENDIF FRAMEWORK_REACT}}
# {{IF FRAMEWORK_VUE}}
CMD ["npx", "serve", "-s", "dist", "-l", "{{FRONTEND_PORT}}"]
# {{ENDIF FRAMEWORK_VUE}}
# {{IF FRAMEWORK_EXPRESS}}
CMD ["node", "{{FRONTEND_ENTRY_POINT}}"]
# {{ENDIF FRAMEWORK_EXPRESS}}
