# =============================================================================
# {{PROJECT_NAME}} — Fullstack Application Dockerfile (Multi-Stage)
# Backend: {{BACKEND_FRAMEWORK}} | Frontend: {{FRONTEND_FRAMEWORK}}
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# =============================================================================

# ---------------------------------------------------------------------------
# Stage 1: Frontend build
# ---------------------------------------------------------------------------
FROM node:{{NODE_VERSION}}-alpine AS frontend-builder

WORKDIR /app/frontend

# Copy frontend dependency files
COPY {{FRONTEND_SUBDIRECTORY}}/package.json {{FRONTEND_SUBDIRECTORY}}/package-lock.json* {{FRONTEND_SUBDIRECTORY}}/yarn.lock* ./

# Install frontend dependencies
# {{IF PM_NPM}}
RUN npm ci
# {{ENDIF PM_NPM}}
# {{IF PM_YARN}}
RUN yarn install --frozen-lockfile
# {{ENDIF PM_YARN}}
# {{IF PM_PNPM}}
RUN corepack enable && pnpm install --frozen-lockfile
# {{ENDIF PM_PNPM}}

# Copy frontend source and build
COPY {{FRONTEND_SUBDIRECTORY}}/ ./

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN {{BUILD_COMMAND}}

# ---------------------------------------------------------------------------
# Stage 2: Backend dependencies
# ---------------------------------------------------------------------------
FROM python:{{PYTHON_VERSION}}-slim AS backend-deps

WORKDIR /app/backend

ENV PYTHONDONTWRITEBYTECODE=1

# Install system build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
# {{IF PM_PIP}}
COPY {{BACKEND_SUBDIRECTORY}}/requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
# {{ENDIF PM_PIP}}
# {{IF PM_PIPENV}}
COPY {{BACKEND_SUBDIRECTORY}}/Pipfile {{BACKEND_SUBDIRECTORY}}/Pipfile.lock ./
RUN pip install --no-cache-dir pipenv && \
    pipenv install --deploy --system
# {{ENDIF PM_PIPENV}}
# {{IF PM_POETRY}}
COPY {{BACKEND_SUBDIRECTORY}}/pyproject.toml {{BACKEND_SUBDIRECTORY}}/poetry.lock* ./
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --only main
# {{ENDIF PM_POETRY}}

# ---------------------------------------------------------------------------
# Stage 3: Production runtime
# ---------------------------------------------------------------------------
FROM python:{{PYTHON_VERSION}}-slim AS runner

WORKDIR /app

# Install runtime system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN groupadd --gid 1001 appgroup && \
    useradd --uid 1001 --gid appgroup --shell /bin/bash --create-home appuser

# Copy Python packages from deps stage
COPY --from=backend-deps /usr/local/lib/python{{PYTHON_MAJOR_VERSION}}/site-packages /usr/local/lib/python{{PYTHON_MAJOR_VERSION}}/site-packages
COPY --from=backend-deps /usr/local/bin /usr/local/bin

# Copy backend source
COPY {{BACKEND_SUBDIRECTORY}}/ ./backend/

# Copy frontend build output
# {{IF FRAMEWORK_NEXTJS}}
COPY --from=frontend-builder /app/frontend/.next/standalone ./frontend/
COPY --from=frontend-builder /app/frontend/.next/static ./frontend/.next/static
COPY --from=frontend-builder /app/frontend/public ./frontend/public
# {{ENDIF FRAMEWORK_NEXTJS}}
# {{IF FRAMEWORK_REACT}}
COPY --from=frontend-builder /app/frontend/build ./frontend/build
# {{ENDIF FRAMEWORK_REACT}}
# {{IF FRAMEWORK_VUE}}
COPY --from=frontend-builder /app/frontend/dist ./frontend/dist
# {{ENDIF FRAMEWORK_VUE}}
# {{IF FRAMEWORK_NUXTJS}}
COPY --from=frontend-builder /app/frontend/.output ./frontend/.output
# {{ENDIF FRAMEWORK_NUXTJS}}

# Create directories
RUN mkdir -p {{LOG_DIR}} && chown -R appuser:appgroup /app

# Expose ports
EXPOSE {{BACKEND_PORT}} {{FRONTEND_PORT}}

# Health check against backend
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD curl -f http://localhost:{{BACKEND_PORT}}/health || exit 1

# Start both services via a simple entrypoint
# In production, use docker-compose.tpl for separate containers instead
COPY <<'ENTRYPOINT' /app/entrypoint.sh
#!/bin/bash
set -e

# Start backend
cd /app/backend
{{BACKEND_START}} &
BACKEND_PID=$!

# Start frontend
cd /app/frontend
{{FRONTEND_START}} &
FRONTEND_PID=$!

# Wait for either process to exit
wait -n $BACKEND_PID $FRONTEND_PID
exit $?
ENTRYPOINT

RUN chmod +x /app/entrypoint.sh

USER appuser

CMD ["/app/entrypoint.sh"]
