# =============================================================================
# {{PROJECT_NAME}} — Docker Compose Configuration
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# =============================================================================

services:
  # {{IF HAS_BACKEND}}
  backend:
    build:
      context: ./{{BACKEND_SUBDIRECTORY}}
      dockerfile: Dockerfile
    container_name: {{PROJECT_NAME}}-backend
    restart: unless-stopped
    ports:
      - "{{BACKEND_PORT}}:{{BACKEND_PORT}}"
    environment:
      - NODE_ENV=production
      - PORT={{BACKEND_PORT}}
    volumes:
      - backend-data:/app/data
      - backend-logs:/app/{{LOG_DIR}}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{{BACKEND_PORT}}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - {{PROJECT_NAME}}-network
    logging:
      driver: "json-file"
      options:
        max-size: "{{LOG_MAX_SIZE}}"
        max-file: "{{LOG_ROTATE_COUNT}}"
  # {{ENDIF HAS_BACKEND}}

  # {{IF HAS_FRONTEND}}
  frontend:
    build:
      context: ./{{FRONTEND_SUBDIRECTORY}}
      dockerfile: Dockerfile
    container_name: {{PROJECT_NAME}}-frontend
    restart: unless-stopped
    ports:
      - "{{FRONTEND_PORT}}:{{FRONTEND_PORT}}"
    environment:
      - NODE_ENV=production
      - PORT={{FRONTEND_PORT}}
    # {{IF HAS_BACKEND}}
    depends_on:
      backend:
        condition: service_healthy
    # {{ENDIF HAS_BACKEND}}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:{{FRONTEND_PORT}}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - {{PROJECT_NAME}}-network
    logging:
      driver: "json-file"
      options:
        max-size: "{{LOG_MAX_SIZE}}"
        max-file: "{{LOG_ROTATE_COUNT}}"
  # {{ENDIF HAS_FRONTEND}}

  # {{IF FEATURE_NGINX}}
  nginx:
    image: nginx:alpine
    container_name: {{PROJECT_NAME}}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/templates/{{PROJECT_NAME}}-nginx:/etc/nginx/conf.d/default.conf:ro
      # {{IF HAS_SSL}}
      - {{NGINX_SSL_CERT}}:/etc/nginx/ssl/cert.pem:ro
      - {{NGINX_SSL_KEY}}:/etc/nginx/ssl/key.pem:ro
      # {{ENDIF HAS_SSL}}
    depends_on:
      # {{IF HAS_BACKEND}}
      - backend
      # {{ENDIF HAS_BACKEND}}
      # {{IF HAS_FRONTEND}}
      - frontend
      # {{ENDIF HAS_FRONTEND}}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - {{PROJECT_NAME}}-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # {{ENDIF FEATURE_NGINX}}

networks:
  {{PROJECT_NAME}}-network:
    driver: bridge

volumes:
  # {{IF HAS_BACKEND}}
  backend-data:
    driver: local
  backend-logs:
    driver: local
  # {{ENDIF HAS_BACKEND}}
