# =============================================================================
# {{PROJECT_NAME}} — Python Application Dockerfile
# Framework: {{BACKEND_FRAMEWORK}}
# Generated by web-deployer skill — {{DEPLOY_TIMESTAMP}}
# =============================================================================

FROM python:{{PYTHON_VERSION}}-slim AS base

# Prevent Python from writing .pyc files and enable unbuffered output
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies that some Python packages need
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        curl \
    && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------
# Stage 1: Dependencies
# ---------------------------------------------------------------------------
FROM base AS deps

# Copy dependency files
# {{IF PM_PIP}}
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
# {{ENDIF PM_PIP}}
# {{IF PM_PIPENV}}
COPY Pipfile Pipfile.lock ./
RUN pip install --no-cache-dir pipenv && \
    pipenv install --deploy --system
# {{ENDIF PM_PIPENV}}
# {{IF PM_POETRY}}
COPY pyproject.toml poetry.lock* ./
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --only main
# {{ENDIF PM_POETRY}}

# ---------------------------------------------------------------------------
# Stage 2: Production runtime
# ---------------------------------------------------------------------------
FROM base AS runner

# Create non-root user
RUN groupadd --gid 1001 appgroup && \
    useradd --uid 1001 --gid appgroup --shell /bin/bash --create-home appuser

# Copy installed packages from deps stage
COPY --from=deps /usr/local/lib/python{{PYTHON_MAJOR_VERSION}}/site-packages /usr/local/lib/python{{PYTHON_MAJOR_VERSION}}/site-packages
COPY --from=deps /usr/local/bin /usr/local/bin

# Copy application code
COPY . .

# Create log and data directories
RUN mkdir -p {{LOG_DIR}} && chown -R appuser:appgroup /app

# Set environment
ENV PORT={{BACKEND_PORT}}

USER appuser

EXPOSE {{BACKEND_PORT}}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD curl -f http://localhost:{{BACKEND_PORT}}/health || exit 1

# {{IF FRAMEWORK_FLASK}}
CMD ["gunicorn", "--bind", "0.0.0.0:{{BACKEND_PORT}}", "--workers", "4", "--timeout", "120", "{{BACKEND_ENTRY_POINT}}:app"]
# {{ENDIF FRAMEWORK_FLASK}}
# {{IF FRAMEWORK_DJANGO}}
CMD ["gunicorn", "--bind", "0.0.0.0:{{BACKEND_PORT}}", "--workers", "4", "--timeout", "120", "{{DJANGO_WSGI_MODULE}}.wsgi:application"]
# {{ENDIF FRAMEWORK_DJANGO}}
# {{IF FRAMEWORK_FASTAPI}}
CMD ["uvicorn", "{{BACKEND_ENTRY_POINT}}:app", "--host", "0.0.0.0", "--port", "{{BACKEND_PORT}}", "--workers", "4"]
# {{ENDIF FRAMEWORK_FASTAPI}}
# {{IF FRAMEWORK_PYTHON_GENERIC}}
CMD ["python", "{{BACKEND_ENTRY_POINT}}"]
# {{ENDIF FRAMEWORK_PYTHON_GENERIC}}
